---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - api.vishant.online
  resources:
  - statefulscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.vishant.online
  resources:
  - statefulscalers/finalizers
  verbs:
  - update
- apiGroups:
  - api.vishant.online
  resources:
  - statefulscalers/status
  verbs:
  - get
  - patch
  - update
