# permissions for end users to edit statefulscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: statefulscaler-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: statefulset-scaler-operator
    app.kubernetes.io/part-of: statefulset-scaler-operator
    app.kubernetes.io/managed-by: kustomize
  name: statefulscaler-editor-role
rules:
- apiGroups:
  - api.vishant.online
  resources:
  - statefulscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - api.vishant.online
  resources:
  - statefulscalers/status
  verbs:
  - get
